name: Publish to PyPI

on: push  # Run the workflow on every push to any branch

jobs:
  publish:
    runs-on: windows-latest  # Use Windows runner since the project runs on Windows
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify Python >=3.6 compatibility

      # Step 3: Clean up old build files
      - name: Clean up dist folder
        run: |
          if (Test-Path dist) {
            Remove-Item -Recurse -Force dist
          }
        shell: pwsh  # Use PowerShell for Windows-specific commands

      # Step 4: Install dependencies
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      # Step 5: Build the distribution
      - name: Build the package
        run: python setup.py sdist bdist_wheel

      # Step 6: Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
      
      # Step 7: Send to alexander@xandyspi.local
      - name: send to xandyspi
        run: |
          $version = "3-20-20"
          $date = Get-Date -Format "dd-MM-yyyy"
          $directoryName = "neelthee_mansion_$version_$date"
          $destinationDirectory = "alexander@xandsypi.local:/home/alexander/Documents/$directoryName"
          
          # Ensure the destination directory exists or create it
          ssh alexander@xandsypi.local "mkdir -p /home/alexander/Documents/$directoryName"

          # Run SCP to transfer files
          scp -r C:\Users\alexa\OneDrive\code\.py\python_stuff\neelthee_mansion\* $destinationDirectory

