name: Publish to PyPI

on: push

jobs:
  publish:
    runs-on: windows-latest  # Use Windows runner since the project runs on Windows
    steps:

      # Step 1: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.6'  # Specify minimum required Python version

      # Step 2: Clean up old build files
      - name: Clean up dist folder
        run: Remove-Item -Recurse -Force dist
        shell: pwsh  # Use PowerShell to run the command

      # Step 3: Install dependencies
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      
      - name: Remove old dist folder
        run: Remove-Item -Recurse -Force dist

      # Step 5: Build the distribution
      - name: Build the package
        run: python setup.py sdist bdist_wheel

      # Step 6: Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
